### ISSUE TITLE
Unable to find and test ctftool.exe

### ISSUE THREAD

**Issue by sranesushant1988** [taviso/ctftool#12]
Hello

I was unable to find ctftool.exe in provided download file hence unable to test and proceed. Can you help me to get the file ?

Thank you

**Comment by KillerRyuk** [comment]
https://github.com/taviso/ctftool/releases Download the zip here

**Comment by sranesushant1988** [comment]
Hey 

Thanks a lot for .exe file. I try testing it on win10 1809 but unable to take privilage of Administrator using normal user account. When i executed "scan" command it came up with followinf error. " failed to send message to server, giving up, 0xc0000008" Later ignored and move forward and executed "script .\scripts\ctf-consent-system.ctf " i got following error "failed to send message to server, 0xc0000041" Am I Doing anything wrong ?

**Comment by sranesushant1988** [comment]
Video Im referering to is https://youtu.be/quenNNqoDBs
